### PR TITLE
Restoring Martialing to fix buffer length issues

### PR DESCRIPTION
**Pull request by ilamp**

### CODE REVIEW

**Comment by wherewhere** [comment]
幽灵幽灵幽灵

**Comment by ilamp** [comment]
@wherewhere I've narrowed the issue down to following line: https://github.com/yungd1plomat/AdvancedSharpAdbClient/blob/766d537d8d12d8a5ccd35409108f5505a8d2101c/AdvancedSharpAdbClient/Framebuffer.cs#L96

` Data = ArrayPool<byte>.Shared.Rent((int)Header.Size);`

Length of `Data` is longer than `Header.Size` after the rent call. I'm going to continue looking into this tomorrow.


Please convert this to a draft so that nobody merges it by mistake.

**Comment by ilamp** [comment]
Looking at the [docs here](https://dotnet.github.io/dotNext/features/io/rental.html) this is an expected behavior so we can't use the length of Data since it can be longer than what we requested.

**Comment by wherewhere** [comment]
OK

**Comment by ilamp** [comment]
@wherewhere All  幽灵幽灵幽灵 are fixed and tests are passing. Please feel free to merge and I'll appreciate if you could bump a new release.

Furthermore, we should probably remove support the EOL .net versions.

**Pull request merged**
