### PR TITLE
Add auto-releasing and upload

### PR DESCRIPTION
**Pull request by yungd1plomat**
Finally got around to doing #69

build and test:
```mermaid
    flowchart LR
        subgraph Test
        WindowsTest(build-and-test-windows-latest)
        UbuntuTest(build-and-test-ubuntu-latest)
        MacOSTest(build-and-test-macos-latest)
        end
        Start([Start]) -->  WindowsTest
        Start -->  UbuntuTest
        Start -->  MacOSTest
        WindowsTest --> IsTestSuccess{Is success?}
        UbuntuTest --> IsTestSuccess{Is success?}
        MacOSTest --> IsTestSuccess{Is success?}
        IsTestSuccess -->|True| PublishNuget(build-and-publish)
        PublishNuget --> End([End])
```
build-and-publish:
```mermaid
    flowchart LR
        Start([Start]) -->  IsMain{Is main branch?}
        IsMain -->|True| Setup(Setup .NET Core App)
        Setup --> Restore(Install dependencies)
        Restore --> Build("Build
        `FullTargets` should be true")
        Build --> BuildNuget(Build the NuGet package)
        BuildNuget --> Publish(Publish to Github Packages)
        Publish --> Upload(Upload artifact)
        Upload --> End([End])
```

### CODE REVIEW

**Comment by wherewhere** [comment]
But I have added in https://github.com/yungd1plomat/AdvancedSharpAdbClient/pull/73/commits/f039ff62b233489fb73bf8447e7dfa6ba48cbdf1

**Comment by wherewhere** [comment]
But failed https://github.com/yungd1plomat/AdvancedSharpAdbClient/actions/runs/6324138058/job/17173093633

**Comment by yungd1plomat** [comment]
> But failed https://github.com/yungd1plomat/AdvancedSharpAdbClient/actions/runs/6324138058/job/17173093633

oh sorry, it's because i'm owner

**Comment by wherewhere** [comment]
So it should provider the secret id...
You need set it in the secret of this repo.

**Comment by yungd1plomat** [comment]
> So it should provider the secret id... You need set it in the secret of this repo.

yes i know, 36758f32219a15a5ed8f048c1d3c14d6bbbea4cc should fix that

**Comment by wherewhere** [comment]
Could you rename that to `NUGET_KEY` or `PACKAGE_KEY`? `API_KEY` doesn't mean which API🤣.

**Comment by wherewhere** [comment]
Coud you please remove this package https://github.com/yungd1plomat/AdvancedSharpAdbClient/pkgs/nuget/AdvancedSharpAdbClient/131947841 🤣
I have added the build number to the version code...

**Comment by yungd1plomat** [comment]
> Coud you please remove this package https://github.com/yungd1plomat/AdvancedSharpAdbClient/pkgs/nuget/AdvancedSharpAdbClient/131947841 🤣 I have added the build number to the version code...

yep

**Comment by wherewhere** [comment]
> yes i know, 36758f32219a15a5ed8f048c1d3c14d6bbbea4cc should fix that. I forgot that the repository is not in the organization

Shall we create an organization called `SharpAdb`? So that we can bring winrt verion and sample app to each repo.

**Comment by yungd1plomat** [comment]
> > yes i know, [36758f3](https://github.com/yungd1plomat/AdvancedSharpAdbClient/commit/36758f32219a15a5ed8f048c1d3c14d6bbbea4cc) should fix that. I forgot that the repository is not in the organization
> 
> Shall we create an organization called `SharpAdb`? So that we can bring winrt verion and sample app to each repo.

yep we can, but my phone is broken right now and I can't do it yet because 2fa.

**Comment by wherewhere** [comment]
🤣🤣🤣

**Pull request merged**
